name = "julia-ecosystem-benchmarks"
uuid = "12345678-1234-5678-9abc-123456789abc"
authors = ["Claude Code <claude@anthropic.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
DataFrames = "1.7.0"
Printf = "1.11.0"
